os:
  - linux
language: go
go:
  - 1.12.x
  - 1.13.x
  - master
services:
  - memcached
  - redis-server
  - mysql
jobs:
  allow_failures:
    - go: master
  fast_finish: true
before_install:
  - go get github.com/mattn/goveralls
  - mysql -e 'CREATE DATABASE test;'
  - mysql -uroot --password="" test < stores/mysqlstore/migrations/1584366110_create_captchas_table.sql
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - go vet ./...
  - test -z "$(gofmt -d -s . | tee /dev/stderr)"
  - $HOME/gopath/bin/goveralls  -coverprofile=coverage.out -service=travis-ci
